openapi: 3.0.3
info:
  title: Sample API
  description: A simple API to demonstrate OpenAPI specification
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local server
paths:
  /:
    get:
      summary: Returns a test message
      x-eov-operation-id: test
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: test
